{% set name = "openpmd-beamphysics" %}
{% set version = "0.9.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 26e375c3819f9f46b836d2223f74c732ce4f5c04b09d6f68d8d4b1b91d49a689

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools    
  run:
    - python >=3.9
    - matplotlib-base
    - numpy
    - scipy
    - h5py

test:
  imports:
    - pmd_beamphysics

about:
  home: https://github.com/ChristopherMayes/openPMD-beamphysics
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Tools for analyzing and viewing particle data in the openPMD standard, extension beamphysics.
  description: |
    Tools for analyzing and viewing particle data in the openPMD standard,
    extension beamphysics.

extra:
  recipe-maintainers:
    - ChristopherMayes
