{% set name = "openPMD-beamphysics" %}
{% set version = "0.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name|replace("-", "_") }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 0a28cbea37c3f7e82f1201655fcc4d0aa254489b00c5fea3dd23a6eb2a34b5af

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - matplotlib-base
    - numpy
    - scipy
    - h5py

test:
  imports:
    - pmd_beamphysics

about:
  home: https://github.com/ChristopherMayes/openPMD-beamphysics
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Tools for analyzing and viewing particle data in the openPMD standard, extension beamphysics.
  description: |
    Tools for analyzing and viewing particle data in the openPMD standard,
    extension beamphysics.

extra:
  recipe-maintainers:
    - ChristopherMayes
