{% set name = "openPMD-beamphysics" %}
{% set version = "0.5.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ChristopherMayes/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d8820329091f706a5a41a008fc293015610354006277fdcdac610a4c989bcb2c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - matplotlib-base
    - numpy
    - scipy
    - h5py

test:
  imports:
    - pmd_beamphysics

about:
  home: https://github.com/ChristopherMayes/openPMD-beamphysics
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Tools for analyzing and viewing particle data in the openPMD standard, extension beamphysics.
  description: |
    Tools for analyzing and viewing particle data in the openPMD standard,
    extension beamphysics.

extra:
  recipe-maintainers:
    - ChristopherMayes
